### ISSUE TITLE
Implement `version` command

### ISSUE THREAD

**Issue by kpitzen** [pulumi/schema-tools#25]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, when running `schema-tools version`, the tool just outputs "TODO". It would be ideal if the tool could output its version at the time of invocation.

**Comment by neverbeenthisweeb** [comment]
Hi @kpitzen , I am interested to work on this issue. Would you mind to assign this to me?

My proposed solution:

- Update cmd to print the `Version` stored in `version` package (see [version.go#L4](https://github.com/pulumi/schema-tools/blob/master/version/version.go#L4)).

```go
// schema-tools/cmd/version.go

Run: func(command *cobra.Command, args []string) {
    fmt.Println(version.Version)
},
```

- Update deployment related files to adjust the value of `version.Version` on build/deployment

Wdyt? Thanks.

**Comment by iwahbe** [comment]
@rafiramadhana Sure. That plan sounds good. 

> Update deployment related files to adjust the value of version.Version

We don't generally adjust the value in `version.go`. We override the version by passing a linker flag: `-X github.com/pulumi/schema-tools/version.Version={{.Tag}}`. That may have been what you meant, but I'm not sure.

**Comment by rafiramadhana** [comment]
@iwahbe Yes. That's what I meant.

**Comment by iwahbe** [comment]
Closed by https://github.com/pulumi/schema-tools/pull/37.
