### ISSUE TITLE
Support for 3rd party providers

### ISSUE THREAD

**Issue by ringods** [pulumi/schema-tools#42]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `pulumi` Github organization is hardcoded in `schema-tools` which makes it unusable to verify 3rd-party providers.

https://github.com/pulumi/schema-tools/blob/ab46109d7ae05f7d388f5bdef068c95bb4b48b9b/internal/cmd/compare.go#L47

### Affected area/feature

Can't use it within Pulumiverse for now:

https://github.com/pulumiverse/pulumi-unifi/actions/runs/5155816412/jobs/9286414047

**Comment by AaronFriel** [comment]
This looks like a pretty quick change to make to schema tools, with a `--repository` argument which accepts an `org/repository-name`, i.e.: `pulumiverse/pulumi-unifi`. When unset, it would use the current behavior. 

Does that make sense to you?

**Comment by ringods** [comment]
@AaronFriel I talked about this with @mikhailshilkov earlier, and I'm working on a contribution. This is indeed the direction except for the value of `--repository`: I will accept a full URL allowing for non-Github SaaS repositories also:

* Github Enterprise (aka on-prem)
* Gitlab (SaaS & on-prem)
* Gitea

**Comment by t0yv0** [comment]
I think this is fixed with https://github.com/pulumi/schema-tools/pull/43
