### ISSUE TITLE
Repository has no license

### ISSUE THREAD

**Issue by Trundle** [pulumi/schema-tools#46]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It's unclear how the code can be used and distributed. As the tools are used in the builds of `pulumi-aws-native` and `pulumi-azure-native`, it would be good to have a license.

**Comment by AaronFriel** [comment]
@Trundle Thanks for flagging this - resolved.

**Comment by AaronFriel** [comment]
For what it's worth, consult your own counsel, etc., I don't believe build tools that are not incorporated in the distributed output are considered as part of copyright licensing. (Image editing tools do not attach their copyright to their output; Go, GCC, LLVM do not, etc...) 

That said, we'll always update our open source repos to make licensing clear when there's ambiguity.
