### ISSUE TITLE
Schema-tools not summarizing property additions

### ISSUE THREAD

**Issue by t0yv0** [pulumi/schema-tools#52]
### What happened?

Double checking automated Databricks update PR.

https://github.com/pulumi/pulumi-databricks/pull/174

It appears that there are were a few small schema extensions, however the summary on the PR is empty 'the schema has no changes'. That is unfortunate as the schema diff does show changes:

```
   "runJobTask": {
                    "$ref": "#/types/databricks:index/JobRunJobTask:JobRunJobTask"
                },
```

### Expected Behavior

If there are changes, even small ones, the PR summary from schema-tools indicates that there were changes so the maintainers can double-check if interested.

### Steps to reproduce

See above PR.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Closing in favor of older #16
