### ISSUE TITLE
An actual small change is not showing through the change report

### ISSUE THREAD

**Issue by t0yv0** [pulumi/schema-tools#73]
### What happened?

During https://github.com/pulumi/pulumi-aws/pull/4025 upgrade

Noticing that the schema is changing slightly but the PR report is empty. 

```
Does the PR have any schema changes?

Looking good! No breaking changes found.
No new resources/functions.
```

While not entirely sure I thought maybe the issue is with schema-tools.

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
IIRC, the PR schema check is only looking for breaking changes; I think that review only had non-breaking, optional property additions.

**Comment by t0yv0** [comment]
Ah so by design? I got thrown off by "Does the PR have any schema changes?". Perhaps "Does the PR have any breaking schema changes or new resources/functions?"
